# Generated by Django 3.2.21 on 2024-04-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(default='', max_length=500, null=True)),
                ('image', models.ImageField(upload_to='qr_code_images')),
            ],
        ),
    ]
