# Generated by Django 3.2.21 on 2024-04-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_decode_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decode',
            old_name='data',
            new_name='decoded_text',
        ),
    ]
