# Generated by Django 3.2.21 on 2024-04-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_decode_api', '0002_rename_data_decode_decoded_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decode',
            name='image',
        ),
        migrations.AddField(
            model_name='decode',
            name='file_id',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
