# Generated by Django 5.0.1 on 2024-04-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qr_decode_api", "0003_auto_20240404_1411"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="qr_images")),
                (
                    "decoded_text",
                    models.CharField(default="", max_length=500, null=True),
                ),
            ],
        ),
    ]
